# Generated by Django 3.2.4 on 2022-10-24 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Estudiante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('last_name', models.CharField(max_length=250)),
                ('email', models.CharField(max_length=250)),
                ('CI', models.CharField(max_length=250)),
                ('parcial1', models.CharField(max_length=5)),
                ('parcial2', models.CharField(max_length=5)),
                ('parcial3', models.CharField(max_length=5)),
                ('parcial4', models.CharField(max_length=5)),
                ('promedio', models.CharField(max_length=5)),
            ],
        ),
    ]
